export const features = [
  {
    label: "What is the property type?",
    variableName: "propertyType",
    properties: [
      "Apartment",
      "House",
      "Condo / Townhome",
      "Secondary Unit",
      "Unique place",
      "Bed and Breakfast",
      "Boutique Hotel",
      "Duplex",
      "RV / Camper",
      "Tiny House",
    ],
  },
  {
    label: "Choose the best option that fits the space in the property that guests will occupy.",
    variableName: "propertySpaceFeature",
    properties: ["The whole place", "A private room", "A shared room"],
  },
];

export const lastOffer = {
  first: [
    {
      lable: "Quiet Neighborhood",
      variableName: "quietNeighborhood",
    },
    {
      lable: "Rare Space",
      variableName: "rareSpace",
    },
    {
      lable: "Good for Families",
      variableName: "goodForFamilies",
    },
    {
      lable: "Sleek Interior",
      variableName: "sleekInterior",
    },
    {
      lable: "Ideal Location",
      variableName: "idealLocation",
    },
    {
      lable: "Roomy and Big Space",
      variableName: "roomyAndBigSpace",
    },
  ],
};
export const propertyDescribe = [
  { label: "Quiet Neighborhood", value: "Quiet Neighborhood" },
  { label: "Rare Space", value: "Rare Space" },
  { label: "Good for Families", value: "Good for Families" },
  { label: "Sleek Interior", value: "Sleek Interior" },
  { label: "Ideal Location", value: "Ideal Location" },
  { label: "Roomy and Big Space", value: "Roomy and Big Space" },
];

export const amenities = [
  { label: "Hot Tub", value: "Hot Tub" },
  { label: "Patio", value: "Patio" },
  { label: "BBQ Grill", value: "BBQ Grill" },
  { label: "Fire Pit", value: "Fire Pit" },
  { label: "Pool Table", value: "Pool Table" },
  { label: "Indoor Fireplace", value: "Indoor Fireplace" },
  { label: "Outdoor Dining Area", value: "Outdoor Dining Area" },
  { label: "Exercise Equipment", value: "Exercise Equipment" },
  { label: "Self Check-in", value: "Self Check-in" },
  { label: "Washer", value: "Washer" },
  { label: "Paid parking on premises", value: "Paid parking on premises" },
  { label: "Outdoor shower", value: "Outdoor shower" },
  { label: "EV charger", value: "EV charger" },
  { label: "Smoke alarm", value: "Smoke alarm" },
  { label: "First aid kit", value: "First aid kit" },
  { label: "Carbon monoxide alarm", value: "Carbon monoxide alarm" },
  { label: "Fire extinguisher", value: "Fire extinguisher" },
  { label: "Bathtub", value: "Bathtub" },
  { label: "Bidet", value: "Bidet" },
  { label: "Body Soap", value: "Body Soap" },
  { label: "Cleaning products", value: "Cleaning products" },
  { label: "Conditioner", value: "Conditioner" },
  { label: "Hair Dryer", value: "Hair Dryer" },
  { label: "Hot water", value: "Hot water" },
  { label: "Shampoo", value: "Shampoo" },
  { label: "Shower gel", value: "Shower gel" },
  {
    label: "Essentials (Towels, bed sheets, soap, toilet paper, and pillows)",
    value: "Essentials (Towels, bed sheets, soap, toilet paper, and pillows)",
  },
  { label: "Clothing storage", value: "SClothing storage" },
  { label: "Dryer", value: "Dryer" },
  { label: "Drying rack for clothing", value: "Drying rack for clothing" },
  { label: "Extra pillows and blankets", value: "Extra pillows and blankets" },
  { label: "Hangers", value: "Hangers" },
  { label: "Iron", value: "Iron" },
  { label: "Mosquito Net", value: "Mosquito Net" },
  { label: "Safe", value: "Safe" },
  { label: "Books and reading material", value: "Books and reading material" },
  { label: "Ethernet connection", value: "Ethernet connection" },
  { label: "Game console", value: "Game console" },
  { label: "Piano", value: "Piano" },
  { label: "Ping Pong Table", value: "Ping Pong Table" },
  { label: "Record player", value: "Record player" },
  { label: "Sound system", value: "Sound system" },
  { label: "Baby Bath", value: "Baby Bath" },
  { label: "Baby monitor", value: "Baby monitor" },
  { label: "Baby safety gates", value: "Baby safety gates" },
  { label: "Babysitter recommendations", value: "Babysitter recommendations" },
  { label: "Board games", value: "Board games" },
  { label: "Changing table", value: "Changing table" },
  { label: "Children's books and toys", value: "Children's books and toys" },
  { label: "Children's dinnerware", value: "Children's dinnerware" },
  { label: "Crib", value: "Crib" },
  { label: "Fireplace guards", value: "Fireplace guards" },
  { label: "High chair", value: "High chair" },
  { label: "Outlet covers", value: "Outlet covers" },
  { label: "Pack ‘n play/Travel crib", value: "Pack ‘n play/Travel crib" },
  { label: "Window guards", value: "Window guards" },
  { label: "Ceiling Fan", value: "Ceiling Fan" },
  { label: "Heating", value: "Heating" },
  { label: "Portable Fan", value: "Portable Fan" },
  { label: "Baking sheet", value: "Baking sheet" },
  { label: "BBQ utensils", value: "BBQ utensils" },
  { label: "Bread maker", value: "Bread maker" },
  { label: "Blender", value: "Blender" },
  { label: "Coffee", value: "Coffee" },
  { label: "Cooking basics", value: "Cooking basics" },
  { label: "Dishwasher", value: "Dishwasher" },
  { label: "Freezer", value: "Freezer" },
  { label: "Hot water Kettls", value: "Hot water Kettls" },
  { label: "Microwave", value: "Microwaves" },
  { label: "Mini fridge", value: "Mini fridge" },
  { label: "Oven", value: "Oven" },
  { label: "Refrigerator", value: "Refrigerator" },
  { label: "Rice maker", value: "Rice maker" },
  { label: "Stove", value: "Stove" },
  { label: "Toaster", value: "Toaster" },
  { label: "Trash compactor", value: "Trash compactor" },
  { label: "Wine glasses", value: "Wine glasses" },
  { label: "Beach access", value: "Beach access" },
  { label: "Lake access", value: "Lake access" },
  { label: "Private entrance", value: "Private entrance" },
  { label: "Resort access", value: "Resort access" },
  { label: "Ski-in/Ski-out", value: "Ski-in/Ski-out" },
  { label: "Waterfront", value: "Waterfront" },
  { label: "Backyard", value: "Backyard" },
  { label: "BBQ grill", value: "BBQ grill" },
  {
    label: "Beach essentials (Beach towels, umbrella, beach blanket, snorkeling gear)",
    value: "Beach essentials (Beach towels, umbrella, beach blanket, snorkeling gear)",
  },
  { label: "Bikes", value: "Bikes" },
  { label: "Boat slip", value: "Boat slip" },
  { label: "Fire put", value: "Fire put" },
  { label: "Hammock", value: "Hammock" },
  { label: "Kayak", value: "Kayak" },
  { label: "Outdoor dining area", value: "Outdoor dining area" },
  { label: "Outdoor kitchen", value: "Outdoor kitchen" },
  { label: "Patio or balcony", value: "Patio or balcony" },
  { label: "Elevator", value: "Elevator" },
  { label: "Free street parking", value: "Free street parking" },
  { label: "Sauna", value: "Sauna" },
  { label: "Single level home", value: "Single level home" },
  { label: "Breakfast", value: "Breakfast" },
  { label: "Cleaning before checkout", value: "Cleaning before checkout" },
  {
    label: "Long term stays allowed 28 days or more",
    value: "Long term stays allowed 28 days or more",
  },
  { label: "Luggage dropoff allowed", value: "Luggage dropoff allowed" },
];
